# Generated by Django 3.1.4 on 2020-12-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=112, unique=True)),
                ('proteins', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('fats', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('carbohydrates', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=112, unique=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('ingredients', models.ManyToManyField(to='api.Ingredient')),
            ],
        ),
    ]
