# Generated by Django 3.1.4 on 2020-12-16 18:09

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_auto_20201216_1459"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="image",
            field=models.ImageField(
                default=None, upload_to=api.models.upload_file_path_ingredient
            ),
        ),
    ]
