# Generated by Django 3.1.4 on 2020-12-19 16:03

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_ingredient_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='image',
            field=models.ImageField(default=None, upload_to=api.models.upload_file_path_meal),
        ),
    ]
